export type Language = "en" | "zh";

export const translations = {
  en: {
    // Page
    pageTitle: "Stock Plans",
    pageSubtitle: "Track and manage your stock option plans",

    // Buttons
    addPlan: "Add Plan",
    exportCSV: "Export CSV",
    cancel: "Cancel",

    // Dialog
    addNewPlan: "Add New Plan",

    // Form Labels
    stockName: "Stock Name",
    stockSymbol: "Stock Symbol",
    searchStocks: "Search stocks...",
    targetPrice: "Target Price ($)",
    deadline: "Deadline",
    action: "Action",
    buy: "Buy",
    sell: "Sell",
    shares: "Shares",
    planName: "Plan Name",
    planNameOptional: "(optional)",
    autoGenerated: "Auto-generated if empty",

    // Price Display
    currentPrice: "Current Price",
    fetchingPrice: "Fetching real-time price...",
    unableToFetchPrice: "Unable to fetch real-time price",
    fromCurrentPrice: "from current price",

    // Table Headers
    plan: "Plan",
    stock: "Stock",
    change: "Change",
    status: "Status",

    // Status
    ongoing: "Ongoing",
    done: "Done",
    expired: "Expired",
    trash: "Trash",

    // Empty State
    noPlansYet: "No plans yet",
    clickAddPlan: 'Click "Add Plan" to create your first stock plan.',

    // Language
    language: "Language",
    english: "English",
    chinese: "中文",
  },
  zh: {
    // Page
    pageTitle: "股票计划",
    pageSubtitle: "跟踪和管理您的股票期权计划",

    // Buttons
    addPlan: "添加计划",
    exportCSV: "导出 CSV",
    cancel: "取消",

    // Dialog
    addNewPlan: "添加新计划",

    // Form Labels
    stockName: "股票名称",
    stockSymbol: "股票代码",
    searchStocks: "搜索股票...",
    targetPrice: "目标价格 ($)",
    deadline: "截止日期",
    action: "操作",
    buy: "买入",
    sell: "卖出",
    shares: "股数",
    planName: "计划名称",
    planNameOptional: "(可选)",
    autoGenerated: "留空则自动生成",

    // Price Display
    currentPrice: "当前价格",
    fetchingPrice: "正在获取实时价格...",
    unableToFetchPrice: "无法获取实时价格",
    fromCurrentPrice: "相对当前价格",

    // Table Headers
    plan: "计划",
    stock: "股票",
    change: "涨跌",
    status: "状态",

    // Status
    ongoing: "进行中",
    done: "已完成",
    expired: "已过期",
    trash: "已删除",

    // Empty State
    noPlansYet: "暂无计划",
    clickAddPlan: "点击「添加计划」创建您的第一个股票计划",

    // Language
    language: "语言",
    english: "English",
    chinese: "中文",
  },
};

export type TranslationKey = keyof typeof translations.en;

